# Generated by Django 6.0.2 on 2026-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="blog",
            name="short_description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
