# Generated by Django 6.0.2 on 2026-02-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_sociallink_alter_about_options_about_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sociallink",
            old_name="platfrom_name",
            new_name="platform_name",
        ),
    ]
